/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BeadsRouteImport } from './routes/beads'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ClaudeAgentsRouteImport } from './routes/claude-agents'
import { Route as DocsContextRouteImport } from './routes/docs-context'
import { Route as EnvironmentRouteImport } from './routes/environment'
import { Route as HelpRouteImport } from './routes/help'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as PromptsRouteImport } from './routes/prompts'
import { Route as RuntimeRouteImport } from './routes/runtime'
import { Route as TailsRouteImport } from './routes/tails'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as ThroughputRouteImport } from './routes/throughput'
import { Route as WorkspaceRouteImport } from './routes/workspace'
import { Route as WorkspaceIndexRouteImport } from './routes/workspace.index'
import { Route as WorkspaceEpicIdRouteImport } from './routes/workspace.$epicId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BeadsRoute = BeadsRouteImport.update({
  id: '/beads',
  path: '/beads',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ClaudeAgentsRoute = ClaudeAgentsRouteImport.update({
  id: '/claude-agents',
  path: '/claude-agents',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsContextRoute = DocsContextRouteImport.update({
  id: '/docs-context',
  path: '/docs-context',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentRoute = EnvironmentRouteImport.update({
  id: '/environment',
  path: '/environment',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsRoute = PromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => rootRouteImport,
} as any)
const RuntimeRoute = RuntimeRouteImport.update({
  id: '/runtime',
  path: '/runtime',
  getParentRoute: () => rootRouteImport,
} as any)
const TailsRoute = TailsRouteImport.update({
  id: '/tails',
  path: '/tails',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ThroughputRoute = ThroughputRouteImport.update({
  id: '/throughput',
  path: '/throughput',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkspaceIndexRoute = WorkspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkspaceRoute,
} as any)
const WorkspaceEpicIdRoute = WorkspaceEpicIdRouteImport.update({
  id: '/$epicId',
  path: '/$epicId',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/catalog': typeof CatalogRoute
  '/claude-agents': typeof ClaudeAgentsRoute
  '/docs-context': typeof DocsContextRoute
  '/environment': typeof EnvironmentRoute
  '/help': typeof HelpRoute
  '/notes': typeof NotesRoute
  '/prompts': typeof PromptsRoute
  '/runtime': typeof RuntimeRoute
  '/tails': typeof TailsRoute
  '/telemetry': typeof TelemetryRoute
  '/throughput': typeof ThroughputRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/$epicId': typeof WorkspaceEpicIdRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/catalog': typeof CatalogRoute
  '/claude-agents': typeof ClaudeAgentsRoute
  '/docs-context': typeof DocsContextRoute
  '/environment': typeof EnvironmentRoute
  '/help': typeof HelpRoute
  '/notes': typeof NotesRoute
  '/prompts': typeof PromptsRoute
  '/runtime': typeof RuntimeRoute
  '/tails': typeof TailsRoute
  '/telemetry': typeof TelemetryRoute
  '/throughput': typeof ThroughputRoute
  '/workspace/$epicId': typeof WorkspaceEpicIdRoute
  '/workspace': typeof WorkspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/beads': typeof BeadsRoute
  '/catalog': typeof CatalogRoute
  '/claude-agents': typeof ClaudeAgentsRoute
  '/docs-context': typeof DocsContextRoute
  '/environment': typeof EnvironmentRoute
  '/help': typeof HelpRoute
  '/notes': typeof NotesRoute
  '/prompts': typeof PromptsRoute
  '/runtime': typeof RuntimeRoute
  '/tails': typeof TailsRoute
  '/telemetry': typeof TelemetryRoute
  '/throughput': typeof ThroughputRoute
  '/workspace': typeof WorkspaceRouteWithChildren
  '/workspace/$epicId': typeof WorkspaceEpicIdRoute
  '/workspace/': typeof WorkspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/beads'
    | '/catalog'
    | '/claude-agents'
    | '/docs-context'
    | '/environment'
    | '/help'
    | '/notes'
    | '/prompts'
    | '/runtime'
    | '/tails'
    | '/telemetry'
    | '/throughput'
    | '/workspace'
    | '/workspace/$epicId'
    | '/workspace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/beads'
    | '/catalog'
    | '/claude-agents'
    | '/docs-context'
    | '/environment'
    | '/help'
    | '/notes'
    | '/prompts'
    | '/runtime'
    | '/tails'
    | '/telemetry'
    | '/throughput'
    | '/workspace/$epicId'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/beads'
    | '/catalog'
    | '/claude-agents'
    | '/docs-context'
    | '/environment'
    | '/help'
    | '/notes'
    | '/prompts'
    | '/runtime'
    | '/tails'
    | '/telemetry'
    | '/throughput'
    | '/workspace'
    | '/workspace/$epicId'
    | '/workspace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BeadsRoute: typeof BeadsRoute
  CatalogRoute: typeof CatalogRoute
  ClaudeAgentsRoute: typeof ClaudeAgentsRoute
  DocsContextRoute: typeof DocsContextRoute
  EnvironmentRoute: typeof EnvironmentRoute
  HelpRoute: typeof HelpRoute
  NotesRoute: typeof NotesRoute
  PromptsRoute: typeof PromptsRoute
  RuntimeRoute: typeof RuntimeRoute
  TailsRoute: typeof TailsRoute
  TelemetryRoute: typeof TelemetryRoute
  ThroughputRoute: typeof ThroughputRoute
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/beads': {
      id: '/beads'
      path: '/beads'
      fullPath: '/beads'
      preLoaderRoute: typeof BeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/claude-agents': {
      id: '/claude-agents'
      path: '/claude-agents'
      fullPath: '/claude-agents'
      preLoaderRoute: typeof ClaudeAgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs-context': {
      id: '/docs-context'
      path: '/docs-context'
      fullPath: '/docs-context'
      preLoaderRoute: typeof DocsContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment': {
      id: '/environment'
      path: '/environment'
      fullPath: '/environment'
      preLoaderRoute: typeof EnvironmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts': {
      id: '/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof PromptsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runtime': {
      id: '/runtime'
      path: '/runtime'
      fullPath: '/runtime'
      preLoaderRoute: typeof RuntimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tails': {
      id: '/tails'
      path: '/tails'
      fullPath: '/tails'
      preLoaderRoute: typeof TailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/throughput': {
      id: '/throughput'
      path: '/throughput'
      fullPath: '/throughput'
      preLoaderRoute: typeof ThroughputRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace': {
      id: '/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workspace/': {
      id: '/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof WorkspaceIndexRouteImport
      parentRoute: typeof WorkspaceRoute
    }
    '/workspace/$epicId': {
      id: '/workspace/$epicId'
      path: '/$epicId'
      fullPath: '/workspace/$epicId'
      preLoaderRoute: typeof WorkspaceEpicIdRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface WorkspaceRouteChildren {
  WorkspaceEpicIdRoute: typeof WorkspaceEpicIdRoute
  WorkspaceIndexRoute: typeof WorkspaceIndexRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceEpicIdRoute: WorkspaceEpicIdRoute,
  WorkspaceIndexRoute: WorkspaceIndexRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BeadsRoute: BeadsRoute,
  CatalogRoute: CatalogRoute,
  ClaudeAgentsRoute: ClaudeAgentsRoute,
  DocsContextRoute: DocsContextRoute,
  EnvironmentRoute: EnvironmentRoute,
  HelpRoute: HelpRoute,
  NotesRoute: NotesRoute,
  PromptsRoute: PromptsRoute,
  RuntimeRoute: RuntimeRoute,
  TailsRoute: TailsRoute,
  TelemetryRoute: TelemetryRoute,
  ThroughputRoute: ThroughputRoute,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
